name: CD

on:
  push:
    branches: [development]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pull and build with SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd fe
          git pull
          cd ..
          sudo docker-compose up -d --build nextjs