name: Deploy Production
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Pull and build with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            cd services
            ./deploy.sh master
