name: Deploy Staging
on:
  push:
    branches: [dev]
jobs: 
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pull and build with SSH
      uses: appleboy/ssh-action@master
      env:
        REF: ${{ github.ref }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        envs: REF
        script: |
          cd services
          ./deploy.sh $REF
